#!/bin/sh

pdflatex cug2013-torque.tex
bibtex cug2013-torque
pdflatex cug2013-torque.tex
pdflatex cug2013-torque.tex

if [ "x$(uname)" == "xDarwin" ];then
	open -a preview cug2013-torque.pdf
elif which evince; then
	evince cug2013-torque.pdf &
fi
