#!/bin/sh

pdflatex cug2013_torque.tex
bibtex cug2013_torque
pdflatex cug2013_torque.tex
pdflatex cug2013_torque.tex

if [ "x$(uname)" == "xDarwin" ];then
	open -a preview cug2013_torque.pdf
elif which evince; then
	evince cug2013_torque.pdf &
fi
